version: "3.8"

services:
  auth-service:
    build: .
    container_name: auth-service
    ports:
      - "8090:8090"
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=adminpass
      - DB_NAME=authdb
    networks:
      - backend-net

  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend-net

volumes:
  pgdata:

networks:
  backend-net:
    driver: bridge
