version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpass
      POSTGRES_DB: authdb
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
