version: '3.8'

services:
  mysql-role-manager:
    image: mysql:8.0
    container_name: mysql-role-manager
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: veterinary_roles
    ports:
      - "3308:3306"
    volumes:
      - rolemanager_data:/var/lib/mysql
    networks:
      - veterinary-network

  role-manager:
    build: .
    container_name: role-manager
    ports:
      - "8084:8084"
    depends_on:
      - mysql-role-manager
    networks:
      - veterinary-network

volumes:
  rolemanager_data:

networks:
  veterinary-network:
