services:
  user-preferences-db:
    image: postgres:15
    container_name: user-preferences-db
    environment:
      POSTGRES_DB: user_preferences
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    networks:
      - preferences-net

  user-preferences:
    build:
      context: .
    container_name: user-preferences
    ports:
      - "8086:8086"
    depends_on:
      - user-preferences-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://user-preferences-db:5432/user_preferences
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks:
      - preferences-net

networks:
  preferences-net:
    driver: bridge
