name: Auth Service CI

on:
  push:
    paths:
      - 'Back-end/Domain 1_Authentication & Security/auth-service/**'
  pull_request:
    paths:
      - 'Back-end/Domain 1_Authentication & Security/auth-service/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Back-end/Domain 1_Authentication & Security/auth-service

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test
