name: CI for profile_image_upload

on:
  workflow_dispatch:  
  push:
    branches: [main, qa]
    paths:
      - 'profile_image_upload/**'
  pull_request:
    branches: [main, qa]
    paths:
      - 'profile_image_upload/**'

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
