name: CI - Bastion Access Service
on:
  push:
    paths:
      - 'Back-end/Domain 1_Authentication & Security/bastion-access-service/**'
  pull_request:
    paths:
      - 'Back-end/Domain 1_Authentication & Security/bastion-access-service/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: Back-end/Domain 1_Authentication & Security/bastion-access-service

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Build Docker image
      run: docker build -t bastion-access-service .
